### ISSUE TITLE
Proposal: Vendoring dependencies using dep

### ISSUE THREAD

**Issue by syadav2015** [LeSuisse/vault-gpg-plugin#12]
Currently it's hard to have a reproducible build of the plugin since the dependencies for this plugin are not vendored. Normally go repositories use a dependency management tool like [dep](https://github.com/golang/dep) to ensure stable dependencies.

I've been using dep to handle dependencies when I'm building this plugin locally. @LeSuisse Would it be okay to send out a PR for vendoring the dependencies of this plugin so that others can benefit from this as well?

**Comment by LeSuisse** [comment]
Hi,

I switched over to Go Modules for my Go projects when Go 1.11 has been released. The go.mod and go.sum files are committed in the repository so you should be able to achieve the same things than with dep.

The vendoring is opt-in with the modules, are you in a situation that needs where the vendoring required?

https://github.com/golang/go/wiki/Modules

**Comment by syadav2015** [comment]
I've been working on adding subkeys support to the the vault-pgp-plugin. I have changes to the crypto/openpgp package (proposal: https://github.com/golang/go/issues/29301), which will be used for subkey related features. However since merging changes upstream is a slow process, I have been using dep to vendor the dependencies for the vault-pgp-plugin source and pointing the the source for openpgp packge to my fork until the changes merge upstream. 

From what I gleaned from the modules wiki, the replace directive should be sufficient for my needs.
