### ISSUE TITLE
Feature Request: Upload key to key server via API

### ISSUE THREAD

**Issue by dataO1** [LeSuisse/vault-gpg-plugin#125]
Would it be possible to extend the API, such that you can upload keys to a key server directly from the API?

The problem i currently have is, when getting the public key via the `read` request , you don't get any deposited metadata like email or real name back from it. In order to upload a key to a key server I have to manually re-enter the key with metadata into the gpg cli and export it from there.

Maybe i'm missing something, but i don't see why some of the parameters, like `email` and `real_name` are needed at all, if i can't really use them.

**Comment by LeSuisse** [comment]
Hello,

> Would it be possible to extend the API, such that you can upload keys to a key server directly from the API?

Since it can be done from outside the Vault context I'm not sure I want to extend the API to handle that especially since there multiple valid options to achieve that. For example some users might prefer uploading their keys to a key server over HTTP or over HKP, others might prefer uploading their keys to Keybase and some others might prefer publish their keys via a Web Key Directory. They are a lot of available options.

> The problem i currently have is, when getting the public key via the read request , you don't get any deposited metadata like email or real name back from it. In order to upload a key to a key server I have to manually re-enter the key with metadata into the gpg cli and export it from there.

This is not expected. Can you please describe your process. I just checked and it seems fine on my side. There is a user ID packet in the public key you can read.

```
$ vault write gpg/keys/test real_name=foo email=a@example.com
$ vault read -field=public_key gpg/keys/test | gpg --import-options show-only --import
pub   rsa2048/0x714AAF99716AED58 2022-01-25 [SC]
 Empreinte de la clef = 0562 E627 4B69 D737 0089  9995 714A AF99 716A ED58
uid                              foo <a@example.com>
sub   rsa2048/0xA934093DA2C626EA 2022-01-25 [E]
$ vault read -field=public_key gpg/keys/test | pgpdump
New: Public Key Packet(tag 6)(269 bytes)
	Ver 4 - new
	Public key creation time - Tue Jan 25 11:37:23 CET 2022
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(2048 bits) - ...
	RSA e(17 bits) - ...
New: User ID Packet(tag 13)(19 bytes)
	User ID - foo <a@example.com>
New: Signature Packet(tag 2)(328 bytes)
	Ver 4 - new
	Sig type - Positive certification of a User ID and Public Key packet(0x13).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA256(hash 8)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Tue Jan 25 11:37:23 CET 2022
	Hashed Sub: issuer key ID(sub 16)(critical)(8 bytes)
		Key ID - 0x714AAF99716AED58
	Hashed Sub: issuer fingerprint(sub 33)(21 bytes)
	 v4 -	Fingerprint - 05 62 e6 27 4b 69 d7 37 00 89 99 95 71 4a af 99 71 6a ed 58 
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to certify other keys
		Flag - This key may be used to sign data
	Hashed Sub: features(sub 30)(1 bytes)
		Flag - Modification detection (packets 18 and 19)
	Hashed Sub: primary User ID(sub 25)(1 bytes)
		Primary - Yes
	Hashed Sub: preferred symmetric algorithms(sub 11)(1 bytes)
		Sym alg - AES with 128-bit key(sym 7)
	Hashed Sub: preferred hash algorithms(sub 21)(1 bytes)
		Hash alg - SHA256(hash 8)
	Hashed Sub: preferred compression algorithms(sub 22)(1 bytes)
		Comp alg - Uncompressed(comp 0)
	Hashed Sub: preferred_aead_algorithms(sub 34)(1 bytes)
		AEAD alg - EAX(aead 1)
	Hash left 2 bytes - ac 4a 
	RSA m^d mod n(2047 bits) - ...
		-> PKCS-1
New: Public Subkey Packet(tag 14)(269 bytes)
	Ver 4 - new
	Public key creation time - Tue Jan 25 11:37:23 CET 2022
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(2048 bits) - ...
	RSA e(17 bits) - ...
New: Signature Packet(tag 2)(310 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA256(hash 8)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Tue Jan 25 11:37:23 CET 2022
	Hashed Sub: issuer key ID(sub 16)(critical)(8 bytes)
		Key ID - 0x714AAF99716AED58
	Hashed Sub: issuer fingerprint(sub 33)(21 bytes)
	 v4 -	Fingerprint - 05 62 e6 27 4b 69 d7 37 00 89 99 95 71 4a af 99 71 6a ed 58 
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
	Hash left 2 bytes - 8d ab 
	RSA m^d mod n(2047 bits) - ...
		-> PKCS-1
```

**Comment by dataO1** [comment]
> There is a user ID packet in the public key you can read.  

I did not know that. I tried your process and it works, sorry I'm pretty new to PGP.

> Since it can be done from outside the Vault context I'm not sure I want to extend the API to handle that especially since there multiple valid options to achieve that. For example some users might prefer uploading their keys to a key server over HTTP or over HKP, others might prefer uploading their keys to Keybase and some others might prefer publish their keys via a Web Key Directory. They are a lot of available options.

I see, i will just publish via the CLI then, its not a big deal. Thanks for the help!
