### ISSUE TITLE
List operation returns 404 when no keys are present

### ISSUE THREAD

**Issue by MLSTRM** [LeSuisse/vault-gpg-plugin#132]
At current if the plugin is mounted and there are no keys stored in the backend, then use of the list /gpg/keys endpoint returns a 404. This feels like a misuse of the status code, and the response should be successful, just with an empty list.

Due to the inability to upsert keys being able to list the keys currently present within the mount is how I've been checking to see if an existing key is present and avoid attempting to update it in place (due to the error response), however if all of the keys are removed then this no longer functions as expected, and I cannot disambiguate this error case from the plugin not existing at all.

version: 0.3.0 (commit a027d043da6)

**Comment by LeSuisse** [comment]
Hello,

Thanks for the report.

I did a quick test with the official transit backend and it seems to do the same thing:
```
$ curl -v --header "X-Vault-Token: ..." --request LIST http://127.0.0.1:8200/v1/transit/keys
*   Trying 127.0.0.1:8200...
* Connected to 127.0.0.1 (127.0.0.1) port 8200 (#0)
> LIST /v1/transit/keys HTTP/1.1
> Host: 127.0.0.1:8200
> User-Agent: curl/7.81.0
> Accept: */*
> X-Vault-Token: s.RU63W97pxUmCVmhcbTlVlRgx
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Cache-Control: no-store
< Content-Type: application/json
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Date: Wed, 16 Feb 2022 18:57:58 GMT
< Content-Length: 14
< 
{"errors":[]}
```

Same for the SSH backend with the roles:
```
$ curl -v --header "X-Vault-Token: ..." --request LIST http://127.0.0.1:8200/v1/ssh/roles
*   Trying 127.0.0.1:8200...
* Connected to 127.0.0.1 (127.0.0.1) port 8200 (#0)
> LIST /v1/ssh/roles HTTP/1.1
> Host: 127.0.0.1:8200
> User-Agent: curl/7.81.0
> Accept: */*
> X-Vault-Token: s.RU63W97pxUmCVmhcbTlVlRgx
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Cache-Control: no-store
< Content-Type: application/json
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Date: Wed, 16 Feb 2022 19:03:22 GMT
< Content-Length: 14
< 
{"errors":[]}
```

I might be missing something but this behavior seems to be match the official backends.

To do the detection maybe you could call the [`/sys/mounts` endpoint](https://www.vaultproject.io/api-docs/system/mounts#sys-mounts)?

**Comment by LeSuisse** [comment]
Closing as it appears to work as expected.
