### ISSUE TITLE
Not able to mount the plugin - pls help with the appropriate command to issue

### ISSUE THREAD

**Issue by ksachdeva** [LeSuisse/vault-gpg-plugin#2]
Hi @LeSuisse ,

I am able to register the plugin in the catalog. Here is a command that shows that it is there -

```
 curl \
    --header "X-Vault-Token: a928f80a-933f-2b5a-3ebc-0db2bbccea89" \
    --request GET \
    http://localhost:8200/v1/sys/plugins/catalog/gpg
{"name":"gpg","command":"/Users/ksachdeva/Desktop/Dev/exp/vaultexp/plugindir/vault-gpg-plugin","args":[],"sha256":"hwiYXMWbljdYehy4mX5I0XmPNQmVKMubJF/86kgJ6As=","builtin":false,"request_id":"34a59bed-6a2e-a117-e44e-bef6a118dca3","lease_id":"","renewable":false,"lease_duration":0,"data":{"args":[],"builtin":false,"command":"/Users/ksachdeva/Desktop/Dev/exp/vaultexp/plugindir/vault-gpg-plugin","name":"gpg","sha256":"hwiYXMWbljdYehy4mX5I0XmPNQmVKMubJF/86kgJ6As="},"wrap_info":null,"warnings":null,"auth":null}
```
However when I try to mount I get following error -

```
> vault mount gpg
Mount error: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/mounts/gpg
Code: 400. Errors:

* unknown backend type: gpg
```

Most likely making an error in issuing the mount command.

Would appreciate if you can guide on how to mount your plugin

Regards & thanks
Kapil

**Comment by LeSuisse** [comment]
Hello,

Your `vault mount` command is incomplete. You did not specify where to mount the backend nor that you try to mount a plugin. You should take a look at the [Vault documentation about mounting and unmounting plugin backends](https://www.vaultproject.io/docs/plugin/index.html#mounting-unmounting-plugin-backends).

According to the plugin catalog response you posted, your command should be something like: `vault mount -path=gpg -plugin-name=gpg plugin`

**Comment by ksachdeva** [comment]
Thanks @LeSuisse.  This makes it work. 

Closing the issue.

Regards
Kapil
