### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by sts** [LeSuisse/vault-gpg-plugin#22]
Can the updated vault/api dependabot commits be already released so the plugin is compatible with the latest Vault versions?

**Comment by LeSuisse** [comment]
Hi,

I wanted to wait for Go 1.13 before releasing a new version of the plugin. Even if they are not built against the latest vault/api module (which is quite recent in the history of Vault) plugins are supposed to continue to work even with the latest version of Vault.

I'm currently running this plugin in production with Vault 1.1.3 with no trouble. I saw that Vault 1.2.0 has been released yesterday but I did not had time to check against it yet.
Do you have some issues with it?

**Comment by LeSuisse** [comment]
Hi,

[v0.2.3](https://github.com/LeSuisse/vault-gpg-plugin/releases/tag/v0.2.3) has been released.
