### ISSUE TITLE
Issue with importing external key

### ISSUE THREAD

**Issue by barnaby0x0** [LeSuisse/vault-gpg-plugin#287]
Hello,

I generated a gpg key and try to import with curl api. To do that I use this json file:
`{
  "generate": "false",
  "key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBGR5l5oBEAC8p4O/c6a/ktP9ckJRP9FvLYZVHM15PK8gy8JJm2DU4SpiMcZW\nw5peMeXlh2uRbiS/bhSoN9nV4E8KZaZ45ywgvaSeS/u5US9zG6+Uocj27qjptR2U\ng7GUYafGAHCcsDf5CLXsGzE9S2AB8Oskbsq2P8vlVHHy5Ls4KCGyMfWEp7UwCzYp\nwlTahRcHNQUFS7LJDHTD/0cn2IfXfnqlkkytB/n3v+2bs3yAa0pWpmNJyO9iWbRm\ndSP5lYlKiu4F5VqDshLE4A0YBO7wzRV59LWyUqvt84lNZcO1jRsy8lUj2SJgo19Q\npTbb4+1eKzQeZIGJLGSyPDzCvUgoa9Ue/sXwkFUk9lOChMTyEsLneCCdljZ+aGsO\nxvW1+jzclYl8ILIr2oazu0hNz1WXgx4yHFJhpQS2udvodL1ZEFgW3GVwLTJ8q0s1\nmzUIHxJ53fS4n4DV3WkMzLjMZtHku5DSVa8Gy6gQhAbknt7IfW3N30qIZk5jm/ph\neO3VSohR/iBEkSXNqlhVBGDoLeSg/5sGFTp6TvSmHiub9G3GXLOOc+ON46si3WMz\nVYFXyR03xQA7N2eLYdLTLB2zI7RSsjXtt3TXey6JeggRgxH8STYAAchAHXUC+6G0\nmgKnJ28duT0VS4kdCYDqrdIxj4wx7YWalRTY3ZNTQz3fzsRQq6SjpgjPPwARAQAB\ntCF0ZXN0MSAoY29tbWVudCkgPHRlc3QxQGVtYWlsLmNvbT6JAk4EEwEKADgWIQS5\nMDDCf14orKOmFjKuecvzok1xFwUCZHmXmgIbAQULCQgHAgYVCgkICwIEFgIDAQIe\nAQIXgAAKCRCuecvzok1xF80pD/0Sry3X4VNaVOz4egNdFEDmMEqW4uZczr41uPAY\nqs4+/FT7mvapMwwEasT3tNmgMmeKrS1aHGXDqIZktfpp6wfj4fYE50P/KHQFZOuG\nGe1L1y9u/jTZaXYJEDninNaiNrIUfUfz7LGLgjQ3FJcTNhFYigK/3tPvV5l64nMz\nszYYoiF7zBjbn0cVxfrYz1+tMqmexdfxWyFmL4r7LmqBM9v6kkwV7zfAcxXn3MKR\nFYBDbcJobtPjsbkTskrpi/BOozOgJkbGP4Q6ZidchzEX4Dd4d7+f0rF5al7OVhO9\nMSspYwPopsciKJCsgsshbGlppW65pWAlw1m210uLtNYF8gX2aAhNMoegF1+pGPwi\nkV+nO+8GTVL/Xxa24y/o7R3AfaBSJtYzx8oJLAOSaNn72sFHUE2XU4qBRCTqMwmT\n+Su0yiOt4oYOrrLFwqTNowiv3Wp5lBNUsHyDYMitwh5f/1sqiEX05ARR+hHv7C1o\n1V0BFFGvKiM93L/d7ZWcjU88SGO3J9TLCZPgNs2gxcJl0+RA8OFi/zJOl1ScuYG+\nQTYgDMjGYrrE8dLcW9CiqYNcWL2Ee9P6aBgWr3EZpTC1W3lcTVMSKZUXdDP2nwRC\nBLqtBXpaG1s/VJdPCebrTCjWDr03c4GLLyFMIyD4IByYTN+TLgHNvPCStP5icu5x\nJmrfIrkCDQRkeZedARAAzfchCj9HLxxWd9UsKXisbqm/Zzfq0uw+FKiIFKdQ32+L\nR9gzheSa5Tr4i9jm1+tWr56mwWExvNxGJeDG23vLWNS9k2IENIl31hd1B4Ptl/dA\n9bbUg+m8hp4ww82Vb5+4ZykpF82UuLNOtV1/1MjEE15QpCrNRS2yiTb7JEpLPn9M\no/2eAP+RUQJeE6HhmlVqDLvDrjPgg/Oa1M1LF86qAUzEMHYo31iECvESB3O3le10\nNOay+I33dKjyO0T1RhYKqxyIMYEse0cyt9r5tSma+6gqE83XHNhJwvp0yHRAd1lf\nBuo7KMn0Sru0LE4Q0MFSQJasXD/ZQIAtk9+i+fMlTAXk3Vce8lC+qXXHADYPS0j1\nG9K1m6mseC1PIYiof89NSGisLAShwTVCAkxoZ/vD4dF/WZxrEkbrKfgap/+JfIeW\nInIR1w6wlddzA9Q6zjwsV4la2zhkLy5YdGkwllS9+imAG8irIRmyGem30ffZOUEt\nAhLw8KC2luDaXHREHDkMQWwsucxTcr1BVCAcJ6k/mGflGCr4Co/1YLRCgpmJTl4e\n3WhdG5H3N8Iaew2/vhzuxaCV/AQrPuq5dZwV/WiuH1hCCOqY8yEDQonqNlz/Rv5J\nnkzTJIURVfQbMAEq6uuZgBdbPsxk6/rivq0u1qZIhiOhSuxEBZuKy1oal03lgu0A\nEQEAAYkEbAQYAQoAIBYhBLkwMMJ/Xiiso6YWMq55y/OiTXEXBQJkeZedAhsCAkAJ\nEK55y/OiTXEXwXQgBBkBCgAdFiEEGgXBJ87suvHTunIzr8Sd1nxEQ7gFAmR5l50A\nCgkQr8Sd1nxEQ7hRAw/5ATlQonw1SNil+WiN8Da8HaAEabuwp/Po35ZAVASKwtnW\nEhyWbfNQ/M1z99Tmo5yWDw5NLeJT9rTxns2siRZWrgxUzRbaG/y7HZ4eMX3uXCId\nn3uGbNzLFm/XF/FpddYT/0xcfwKmZfmoOGn4tvhF+kASJ/Pe65Nk7xFFwXJuJ9Qx\nc+jNQtLRCJkuvoDIuhNTujruGuRMfy3Zi6dbV1KtHQdnXV8p6wxG/95PnIIg5vpt\nQGrqRHABfep1X20vARL348D8vc7TJSMBhrOZcMSFE4f+XTD1PPNmzR8j+l2mNl8y\nza7S4/96e9P83FMONvnzULUzGVcokgyKGmYwTqEMgXpfMRD/PyAUjTP1L+eVjoET\nxlv0xFIBcZDidO75dWL/WBoCJ0k/ikUcRhtmwRiy6NKHP/5ebvCzsSYm6/+WEuHP\nM5hwvDo9T3A9QqeVnp724UvZnApj9t0B5UQWrQK56oCRWhdeVsYLUWgNGTDicgvf\nJGmqX9gnndDQbyidms0SkkSooamcKMMGdb4hB7fWKa7VNggWTZDkNBvreZjeS8mo\neGU8GW7YVCbXM8XCH4LEsqxJZvFDPoGJ4dxn78hXJWEps1KJhnGG2YZtX6J8v+9o\nbvot8IIq7Lc/5Ad/2xhodpPOh3pUr6Cs2VFfJv1Gu5VVrNFQBoVIvye2H9W/IYO1\nsQ/7BHEd4LeoKb11yc2BuGxHiQUEnM7gSsNE9TjCxuXrTn5WgaBY46676oLY4Lzg\n2Py3hBOebhPnHOc+0DsWGtpBh7qZig9n1YDr4ZS1eJbYo+OaJIaZBIp6q3QlXNbG\nSvD7D+mY88iyNox3sabSy1cl2lubSrhKabYidK93PJ3J6Xjai12cOdDRxR+aQBeL\nKu0QQMPmR29TXlX/nn2AHYMfA9wqpIJjjjXbZtljT+FBaT9QqF1gm3PNKQdqzaTE\n5PsXPGBvadUi3AXArlV7wuEnF6/CoaFiO8ORF55AyDRwJrqgyrK69TDfSo2dAn+s\nttUFCsEQCUz74J4WZr+F3p6a70WaQ6NsFBrjEQb/5yYCjxbBmSIRRjfsaWZubZPa\ns8EtfJ/wt/gjo2CyfGhuJ9t6sL7KLMPjC6Dn0ABHi31qxPoxCWwqNL3ZAJMVm1i5\nvDssPjDFYmSSxgKg2Chl2ilxP6v0VbokJmuDBr+PEf10DkOlIzD3eFw7Vm4rZFRr\nd5vXKlQpPa7vjxAgs8xQR7/Mswbifs/EiNBZHPQ4TJO8RLSvAWHbGLgt6SVQr2lf\nuMPRF6kbaMTOPBzU9S2inmXJ/ce5HmbhBufmrKZskU9wTvX/KfSnepJBM+DgMO2e\n4SuBri19i1b1ajMgK1NUVJ6RFFZ3EWzkOquxikPRHdXZiPO5Ag0EZHmXoAEQANQn\n+EfV9w4TrG/XBuW2Kes6RbpvRDwnmiqG/3BaClGU3HKvoVyWYfhcO4Hmeb1jz3Jn\nwkk64tjRT/XXjPU0JsCvNoX2saOS7nx0eiKEUiTdiql8hs78NU3wpx6wLU8rmefF\neKSfs/T3b2fyCl4vu7EI+/XqnRs7n1pZpL8DQoUeHH4xuIw7pY68ONVmOSTWmwSB\nGcGeJpGEGFbO5ZF6M2hXMX92tGhn05PH8LTR0OdmqFwm+cRMzq9rIagDam0b4GWN\nE0g7Tm8NgXVZfeZ6y6SpdSvIBTpCYXD7zHJtHFbbA3TkGzu+MZ+g3W94xKobp2D1\n/vf3oPiyCoS1ekfhnq6ownwVtgerbZHuqZGgLccWiM+SNHtLBQA69iwJh829j5IW\nkNHIQ3+y7JYrTxNJNvrLLMPK5HfSigWhU6JPYYBsaTiWTuax/xwhlP6jCm+mTvuv\nigYvnNpY/BVbtTzTGE3iDqwQWJElA3XhM8Svi823Ep9350sz6rwIbJjkE5YfVz2G\nUbZ6XT4WK2tPbV3k6RnvgAbCQI76GLXqHKMf2NRzJbK+cfP3mqvpU55mMHDyJEDZ\nzsFpEB9c6pVkNyNzYSKTKXjFhsi1D+pBR4rY0hWwIcMJNdaIudbdk5t9JYrNgKVB\nbQk1HgRcs/FxCdi09qqGRVk7RN5MTT/B6uZzjg0RABEBAAGJAjYEGAEKACAWIQS5\nMDDCf14orKOmFjKuecvzok1xFwUCZHmXoAIbDAAKCRCuecvzok1xF+pVD/90dkbb\ndA6tulQf3HldPvuoPIh7feGsOKBjKkSxf9Z1Mu3skHQ4fOBtWVEfCy9CysxdixJB\n+u848vlWWAhrY2CHdWzkFgli9bli04fXElY6Z2QhUqVd/Qkj4yfh0JZuf9CUzK+F\nldpvlhtwlAuMwULoCzwytCFC8DUvhNDGvbQ49oHrSOOr6rgjr3FtGOwdqqGfHu5v\n9NB8DMcruPqnlhamnr74S2K5aZHm3UVuwDmN8N13QREME7vJLeY90+JHA8/EO7SD\nYvLyBt5UolQZ07eTGrfu+roaohFGwxx88ZiTWp9GEVLKyG8cpIcWtbvvrDom6+4q\nylv3+HEeTE6F5tq2AvsjKPyKRBOtVzhtjgvZWZHh00tJQI+LwUW1Z3uoqwTawN5o\n02YREVDy51cQ56ywYkewvIBRAq5aBZCkcmkMa0ODZzpp6xMxUFMiBYiQvGXVBN0t\nmxHVUX1zzbxtv6jEsR3ah7gUIyC35+Nuie/5l6AFU9Nbu32T+0/JmKTH1BDej39C\nGmmt9HM/VV7NtXMLLLNJcNkTvjs1H/OJoz6EAjyqJ8NxOLFz2pe/rOQy+uYO2Pec\nSWsUlwGQhohBMM8k8liiHEEV8Cx2c5NwZZVH0xpeOoDboOWh9cSl8VBPEOhQ/GSN\n5WllcoNhn+P+r/teWkK43MjyDU3iEMxVdvwxSbkCDQRkeZehARAA20u9rzz0ACwv\nS3XBD0TOmbf7h3w+jaemw2x2c+VfirkqLIiwzFnzzNhI3EzvDFacUGTKGLalHPFX\nHhLT1MmaF2Uz3rv3Y2qycoSlKjCp9wGSANUaTJRkMWzX0RX5hnc6N7QkOBE9G3lN\njLuMi5ur2Dr6gzIZy6M8TlXPqsZcUJgl9TKhKoCLzgyRbaQN9h8pm1bvzIbJ9HPV\nE8AhKMZcNDx4cIkNZWySnmD/f4TMS36/c9WIGDwb6q82Wm/Xv2LH2Cx14rhsBcI+\nZFcEArmasgyHVxdLKUYXPODHCitPbXq6eTYtcD+ckr2PHL00cuAPcKZu06UMg9j5\nhVT78pzwWKGX6A2kZXku1S/owCZRoIlQ47jXt74C96XBMw5FXoxbiAUbSMAXc21p\nouDAm8dQGWRdJe2tm4wkDlWSgh5M+ywiKlDIMWJFiJ8FcSBKZtgMS3FswJPl589u\nEvlwFN/lX1FB2N/FU27uEpTL53hJ4dW0AsNKqteGMCRWoejAaNaiKXvgS18Ttnlj\nBgoDIBpiZxy3UAya7zvvgHedOlc1+vY46glYEDbLcS20IOhI/hIvblH0t/fZi3P+\nKSFoNOwPyiY9IrSXa/ya0km21pBtv6PYh7hPhnm3peF4Tr5DoWZd3SbuJZVHQeUg\ndluGFdMGMBrvY574B9tVjoT+s3MGuekAEQEAAYkCNgQYAQoAIBYhBLkwMMJ/Xiis\no6YWMq55y/OiTXEXBQJkeZehAhsgAAoJEK55y/OiTXEXZhwP/isQ7upV0sQPsJSC\nSGNMoasbmK5v4K6YpbdaRT5QXVuH3ujzeRMA5z8M7eyIyI2OWnAuDdLac11pupVW\nxxfACIr9PyNi8pluAdqTT2uvw8Ff9mvwJ9EVeCW9JaHaH6qBVvdjoFC2iG8rH67/\nEIX064Mp0mbu/Y8ZuycVHsSPUeSVZONr/V8JVGXeyptKbpnv+2d+10ZvXMvBZkgv\nj1Dlxy7mfva8UThWDcDW9QPGb9mmZrrnRneBzaTZJRGpI4mU/6mtNPomao/ySv42\njf249BZ8oe0t/itsRHvbrrG3feH86Axf2geO/tImjjBnXjTGgRZrBinnea7iw+L7\n+bWsKwx2HCvg3tyGMaK2GHA4ql6hlS0SeOJ63hjqC3GcdI1Kbu52F7rXfYNQuGqi\nV4mUWdK3+gmxGNw8+pjVcQxXdmMEkRYEpkgv5LfbH2Logx8aD+TFERQdS5hRPmJu\nUCgT/QZQnI0S+4figzhNByYIHraaXjwrnioe+38eXMa2fCOa7GCmsvgxj5bmX4av\nmu639l4nIyTIHp498n3G143M5bQI0jjikplZ1kDu2lyLYl6vArDXqpKdT0s6PrFF\nIZHGQvGAkuM+gpz7D1f5ymJ9WYAByX3Usd7ZygilqMhK5j8TuG4QgqAqtY9sKOtE\nKGRwNEMQI6p3xxlbAR0o7PTYhcXJ\n=2+MK\n-----END PGP PUBLIC KEY BLOCK-----\n",
  "exportable": "true"
}`

And the command:
`curl --header "X-Vault-Token: hvs.B2oGz1YaL8hWclxXKQlTwoLi" --request POST --data @requests/import_key.json http://127.0.0.1:8200/v1/gpg/keys/test1`

But I get this result:
`{"errors":["the key could not be serialized, is a private key present?"]}`

Also when i delete `"generate": "false",` from the json it seem to works.

I don't understand what it going wrong.
Thank you

**Comment by LeSuisse** [comment]
Hello,

> And the command: `curl --header "X-Vault-Token: hvs.B2oGz1YaL8hWclxXKQlTwoLi" --request POST --data @requests/import_key.json http://127.0.0.1:8200/v1/gpg/keys/test1`
> 
> But I get this result: `{"errors":["the key could not be serialized, is a private key present?"]}`

As the message say there is no private key in the message you are trying to import, without a private key there is nothing useful this Vault can do with it. See also #102.

> Also when i delete `"generate": "false",` from the json it seem to works.

It does not at least not in the way you expect it I guess. A new key will be generated.

**Comment by barnaby0x0** [comment]
Thank you for the quick answer and for your work, sorry for the inconvenience was my mistake, now all is working perfectly.
