### ISSUE TITLE
sign docker images

### ISSUE THREAD

**Issue by stafwag** [LeSuisse/vault-gpg-plugin#47]
Hi,

Are there examples/howto available on howto use this to sign docker images?

cheers,

--
staf

**Comment by LeSuisse** [comment]
Hi,

Docker images does not rely on PGP/GPG to sign images. The [Docker Content Trust](https://docs.docker.com/engine/security/trust/content_trust/) uses something called [Notary](https://docs.docker.com/notary/getting_started/) which is based on [The Update Framework](https://theupdateframework.com/) to sign images.

I'm guessing you really wanted to sign images with GPG, you can export the image into a tar archive with `docker save`, sign the resulting the tarball and then distribute both the tarball and the detached signature. Users could then verify the signature and if the signature is correct, import the image with `docker load`. To be honest I recommend against this sort of solution. It's not how the rest of the Docker ecosystem works and to do that with the plugin you will be forced to upload the whole tarball to the Vault instance which can also be problematic (see #4).

**Comment by stafwag** [comment]
Hi,

Thanks for your answer.

It true that docker and the docker registry uses Docker Content Trust and Docker Notary. 

RedHat and quay.io also as GPG for image signing https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/signing_container_images

Skopeo https://github.com/containers/skopeo lets you add a GPG signature to an image, but I didn't see an easy to integrate this feature with a tool like Hashicorp vault.

Anyway, your answer indicates you didn't try it either. I'll look further on the possible options.

Thanks for your nice tool!
