### ISSUE TITLE
HVAC-like Python API?

### ISSUE THREAD

**Issue by trishankatdatadog** [LeSuisse/vault-gpg-plugin#48]
First, thanks for your plugin!

I wonder if you would be interested in a [HVAC-like Python API](https://github.com/hvac/hvac)?

You can take a look at my [WIP](https://github.com/LeSuisse/vault-gpg-plugin/compare/master...trishankatdatadog:trishankatdatadog/python-api), which extends HVAC to include an API to your plugin. WDYT?

**Comment by LeSuisse** [comment]
Hi,

Thank you for your interest and sorry for the delay of my response.

This look nice but I'm not sure it's necessary to integrate it in this repo. It looks like it would as easy to maintain this extension into its own repository. We could add a link to it at the beginning of the README of this repository to ease its discovery. That being said I'm not strongly against merging it here but I'm not sure to see the advantages.

What do you think about this?

**Comment by trishankatdatadog** [comment]
Makes sense to me. Let me separate the code soon. Thanks!

**Comment by LeSuisse** [comment]
Do not hesitate to open a PR or reply here so I can update the README to mention your plugin :wave:
