### ISSUE TITLE
Key Import issues

### ISSUE THREAD

**Issue by fear1226** [LeSuisse/vault-gpg-plugin#84]
Hi, 

We are using this plugin to generate gpg keys in vault and import the keys to encrypt/sign data outside of Vault. 

We have one application server where the key import fails because it expects this text "Version: GnuPG v2" in the key block. 

Do we have to make changes to the GPG version installed on our server or is there a possibility to generate key with this text? 

Thank you.

**Comment by LeSuisse** [comment]
Hi,

I just tried to import a public key GnuPG 2.2.27 and it seems to be fine. Do you have a full repro case that I could investigate?

**Comment by fear1226** [comment]
Hi,

We have generated a key through this GPG plugin in vault. The public key was fetched by the application team and while importing it to the application server , it throws below error.

{
    "message": "PGP key contains no signing key"
}

The key generated through this plugin does not doesn't have the line "Version: GnuPG v2" in it, which is expected by the application server.

Is there a possibility of generating a key through this plugin with version text line in the key block as shown in the example below or any other suggestions which could solve this issue.
![example GPG key](https://user-images.githubusercontent.com/72661093/117746239-b67d4b80-b229-11eb-816a-c3cea5d463d1.png)

**Comment by fear1226** [comment]
Hi 

Thank you for your detailed response.

Is there a way we can use any parameter which adds the version header to the key or create a key with a version header using this vault-gpg-plugin?

**Comment by LeSuisse** [comment]
There is no such option in the plugin and I'm not sure this something belonging to the plugin.

The exported key is valid and as you can see can be imported with GnuPG. The armor header are not protected in any way since they are not part of the message, you can add them yourself in your code when you pull the key from Vault.

**Comment by sidbose87** [comment]
Hi @LeSuisse, version header is usually there when a key is signed, The application is not using GnuPG, it's Tibco MFT, which expects a signed public key which has the version header when it is signed key. So is there a way this plugin can create a signed key and the signing key can be vault's internal key?

**Comment by LeSuisse** [comment]
Hello,

> version header is usually there when a key is signed

The spec says it is not mandatory and adding it leaks more information than necessary so it's not unusual to disable/not set it.

> The application is not using GnuPG, it's Tibco MFT, which expects a signed public key which has the version header when it is signed key.

I suggest to reach out to your support contact because this behavior is incorrect.

> So is there a way this plugin can create a signed key and the signing key can be vault's internal key?

ATM no there is not, that said you can add the headers you wish yourself since they are not protected by any of the signatures of the message.

If I take back the previous message, does something like this work on your app?

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Vault GPG Plugin

xsBNBGCaLJMBCAC/0m0HYOcKEDbZWxnwdiihFSb5BETwcGxPIwyz4JgBYy70BiqA
ln6tZYhdGxkGXQt7i9fovTzEjfmWwesMZ65sFSHWnB4kim60BG9oJq2OORka4HK+
56lO5OeYuLqOr36QgRIcXZRFd5q8nbtgiDL3CVJMjQerGRFt9PIvRecwQ/6cX8Pe
Q+N1XoxZaS5POXUz79g0/D+wtQZ0fN7QoJlFY/m/BiMDWiaTvCKIBrQQk5bSeC3D
aO4/xV1kxeZMO/C4ziCPWyTJ6pEL/eghyrekX5o5/RLl0PyheVEgV3/doXm1lPsm
ioCXXwOzMNIgdJMNO1CpKpw8HJKliIbFhs3JABEBAAHNHUV4YW1wbGUgPGlzc3Vl
ODRAZXhhbXBsZS5jb20+wsBiBBMBCAAWBQJgmiyTCRAOmvwlWuHW2wIbAwIZAQAA
2OMIAKJqc0bORBWm4pWAxvzSu19C7TdMOSDL+A6l0j5MqIlmiyaHcvXQuj5xRK2h
XU37D/VQbkb9eZUse4U36S3uEKr2WHFHFel8FgCyZVYB7Rv/eIL78e7n4BgEpXAT
az7hjLnesmj1+mlM1n08f416GPJfVFqtmKSBP+U6OGwQFGdPrv+hJNfnQFLi5vrQ
LnfQbbUcoPRsMG2c7pnYHKQ1zIK13xgu3u1i2FX5ylMnthtc+h6ryQ2IUoei8VGX
m7AmZ6hCRpiInP7YrYf9NynLMWEmaEk/JDbiWXah2d1AKIqUhZ4+JjFu4xXEKeoa
l5KnJhia4JFuxdFN2+RmUa2LMA/OwE0EYJoskwEIANFzwR5UhdbUxsGmSAxzSQ/t
cTKbW0FgiryGM0Iv+qUTVLQMHRJWMPLNpnn29wTYHrFWLGaWk5m7wrFOoU12Yvog
WeteFwtsGD+EavpxJ0uNpUbPIZFfxMh9bK6sEbqWrSZ+Qi/7KTdEL1KLzeu/9Zow
ltMagljT1PH6wrnMkVHi9mfww29I+d4MOcOi/UmKRCJ8fb1iJdW1+6X6ZhitRmVu
i3/kaLPpkRXmOF4T1OqA55qrcqq2yBqQ8RFwuo4ymYaPPSr9qmlTBRswcRvchPz5
P5SVzVtWCN2EGlTDFH4zb7q2YhZHP0J9awcFDysKuMcVuN6FEDoxbWlQizQ9pkUA
EQEAAcLAXwQYAQgAEwUCYJoskwkQDpr8JVrh1tsCGwwAAJaYCAAx1ZXhwVzitMh/
w6+2LF4+hGKlXNK1itjKOK35kPvF5wb1ZaN55gGw5khzlaVpftdN/QNG3uvfcyu2
6/1VhiSSgA8T/7M9N9RKLC1Pnw2rCrHjSDcL8n9lhaS5ZXJBHxgksrHUtz7d6P1x
/qQXPwVFus7cC6LatVUdkb9yP6Rq0Ah1P10PSOMLuUNX/xD7omcBm54F5KLINsf4
1Jc3F6fQIIxD8fs3BC6xPA1FVz6q/7VFFD0IZENqmpU/uDi0rZxtpoOBTKt39i/H
enfGjRR+If9aFhbOBrM2cyLZZn2tR0p7YAPkFRahE4deeGBX37l0nvjbkTO7U7EG
295MNM+r
=0Rzj
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by LeSuisse** [comment]
Closing as it appears to work as expected.
