### ISSUE TITLE
Memory usage.

### ISSUE THREAD

**Issue by hummerbliss** [LeSuisse/vault-gpg-plugin#9]
Hello,

Was curious as to why the plugin would want to allocate more memory than vault itself. Any insight appreciated.

The screenshot below shows the usage as reported by top(sorted by memory) after starting up vault and getting LISTING GPG keys.

![plugin](https://user-images.githubusercontent.com/1209032/38298325-aa0e2c94-3814-11e8-9026-a49ef707c6ba.png)

Thank you.

**Comment by LeSuisse** [comment]
Hi,

I'm going to need to do a proper memory profile to be sure. 
If the only thing that is asked to Vault is to list the keys I'm not that surprised the plugin ends up using more memory than Vault itself. In this scenario, most of the work is done by the plugin itself.

It is not a behavior I have spotted on my own production instances. Does it cause you an issue or is it just curiosity?

Also, how many keys are we talking about?

**Comment by LeSuisse** [comment]
Hi,

So out of curiosity I have extracted a heap profile of the plugin after a key creation and a listing of the keys, see [heap_prof.pdf](https://github.com/LeSuisse/vault-gpg-plugin/files/1886526/heap_prof.pdf). Most of the memory is consumed outside of the plugin code by itself in the Golang OpenGPG library (which was expected with this use case) and in the interface used for the communication between Vault and the plugin.
Not sure if I can improve things a lot in this area :/ .

**Comment by hummerbliss** [comment]
Hi, thank you for the insight. I am closing issue.
